# ------------------------------------------------------------------------------------------------------
# Extracting meteorology data & calculating growing degree days (GDD) for the 
# different sites for which we have Oak phenology data from NPN + Morton Arboretum
# Christy Rollinson, crollinson@mortonarb.org
# 8 February 2017
# ------------------------------------------------------------------------------------------------------

# -----------------
# Workflow
# -----------------
# 1. Read in list of sites for which we need met; add Morton Arboretum to the list
# 2. Extract daily mean temperature from Daymet (using Daymet so we get day length & not just tmean)
#    - variables to extract: tmin, tmax, daylength  
#    - store as 3D array: dim1 = day of year, dim2 = site, dim3=year
#    - variables to calculate: tmean
#    - Options for extracting Daymet: THREDDS/OpenDAP; FedData (THREDDS probably better so you don't download whole tile)
#      - Daymet will work well for point data, but we'll probably want to use PRISM for continuous wall-to-wall data
# 3. Calculate Climate Thresholds:
#    - GDD5: growing degree days with base temperature = 5 C
#    - nChill: number of days with temperature below 0
# 4. Save data for use later.
#    Option A: netcdf file with 3-dimensional variables for tmin, tmax, tmean, GDD, precip?
#              dim = c(day, year, site)?
#    Option B: separate netcdf file for each site; dim=c(day, year)
#    Option C: separate netcdf file for year year; dim=c(day, site)
# -----------------
# ------------------------------------------------------------------------------------------------------
library(stringr)

# ------------------------------------------------------------------------------------------------------
# 1. Read in list of sites for which we need met; add Morton Arboretum to the list
#    NPN csv file generated by Parth & Lucy, 8 February 2017
# ------------------------------------------------------------------------------------------------------
sites.spp <- read.csv("data/aggregate_npn_oaks.csv")
summary(sites.spp)

# Finding unique sites
# I know I asked for things by species, but if there are multiple species to a site, it doens't
# make sense to do the met extraction more than once
# Aggregating to find how many species are at each site
sites <- aggregate(sites.spp$Species,
                   by=sites.spp[,c("Latitude", "Longitude")],
                   FUN=length)
names(sites)[which(names(sites)=="x")] <- "n.spp" # our "x" value is the number of species in what y'all gave me
summary(sites)

# Note: 1 site has no lat/lon and so it's not really useful, so we're going to remove it
sites <- sites[sites$Latitude>0,]
summary(sites)

# Seeing how many sites this leaves us
nrow(sites) # 742 sites!  That's a ton!

# Out of curiosity, finding what sites have multiple oak species
nrow(sites[sites$n.spp>1,]) #125 sites have 2 or more species observed (that's great!)
# ------------------------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------------------------
# 2. Extract daily mean temperature from Daymet 
#    (using Daymet so we get day length & not just tmean)
# ------------------------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------------------------


# ------------------------------------------------------------------------------------------------------
# 3. Calculate Climate Thresholds:
#    - GDD5: growing degree days with base temperature = 5 C
#    - nChill: number of days with temperature below 0
# ------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------------------------
# 4. Save data for use later.
#    Option A: netcdf file with 3-dimensional variables for tmin, tmax, tmean, GDD, precip?
#              dim = c(day, year, site)?
#    Option B: separate netcdf file for each site; dim=c(day, year)
#    Option C: separate netcdf file for year year; dim=c(day, site)
# ------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------
